FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu20.04

RUN apt update && DEBIAN_FRONTEND=noninteractive \
    apt install --no-install-recommends -y build-essential software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt install --no-install-recommends -y python3.12 python3-pip python3-setuptools python3-distutils && \
    apt clean && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip

WORKDIR /duui

EXPOSE 9714

COPY requirements.txt python/requirements.txt
RUN pip install -r ./python/requirements.txt

COPY python/chunking.py python/chunking.py
COPY python/labeling.py python/labeling.py
COPY python/model/bertopic_model python/model/bertopic_model

COPY python/typesystem.xml ./typesystem.xml
COPY python/communication.lua ./communication.lua
COPY python/bertopic_zeroshot.py ./bertopic_zeroshot.py

EXPOSE 9714

ENTRYPOINT ["uvicorn", "bertopic_zeroshot:app", "--host", "0.0.0.0", "--port", "9714"]
CMD ["--workers", "1"]